=== jonsubs/chrest/build/classes/PairedAssociateFastSlow/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="experiment">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="stimulus-response-pair"/>
        <xs:element ref="fast-presentation"/>
        <xs:element ref="slow-presentation"/>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="auditory-loop-priority-unique">
      <xs:selector xpath="stimulus-response-pair"/>
      <xs:field xpath="auditory-loop-priority"/>
    </xs:unique>
    <xs:key name="stimulus-response-pair-key">
      <xs:selector xpath="stimulus-response-pair"/>
      <xs:field xpath="pair"/>
    </xs:key>
    <xs:keyref name="fast-presentation-cumulative-error-pair-ref" refer="stimulus-response-pair-key">
      <xs:selector xpath="fast-presentation/cumulative-errors/cumulative-errors-data"/>
      <xs:field xpath="pair"/>
    </xs:keyref>
    <xs:unique name="fast-presentation-cumulative-error-pair-unique">
      <xs:selector xpath="fast-presentation/cumulative-errors/cumulative-errors-data"/>
      <xs:field xpath="pair"/>
    </xs:unique>
    <xs:keyref name="slow-presentation-cumulative-error-pair-ref" refer="stimulus-response-pair-key">
      <xs:selector xpath="slow-presentation/cumulative-errors/cumulative-errors-data"/>
      <xs:field xpath="pair"/>
    </xs:keyref>
    <xs:unique name="slow-presentation-cumulative-error-pair-unique">
      <xs:selector xpath="slow-presentation/cumulative-errors/cumulative-errors-data"/>
      <xs:field xpath="pair"/>
    </xs:unique>
  </xs:element>
  <xs:element name="stimulus-response-pair">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="auditory-loop-priority"/>
        <xs:element ref="pair"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="auditory-loop-priority" type="xs:integer"/>
  <xs:element name="fast-presentation">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="percentage-correct"/>
        <xs:element ref="cumulative-errors"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="slow-presentation">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="percentage-correct"/>
        <xs:element ref="cumulative-errors"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="pair" type="xs:string"/>
  <xs:element name="percentage-correct">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="percentage-correct-data"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="percentage-correct-data" type="xs:decimal"/>
  <xs:element name="cumulative-errors">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="cumulative-errors-data"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="cumulative-errors-data">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="pair"/>
        <xs:element ref="cumulative-error"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="cumulative-error" type="xs:integer"/>
</xs:schema>

=== jonsubs/chrest/scripted-experiment-inputs/PairedAssociateFastSlow/12-pairs-input.xml
<?xml version="1.0" encoding="UTF-8"?>
<experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schema.xsd">
    <stimulus-response-pair>
        <auditory-loop-priority>1</auditory-loop-priority>
        <pair>B I W : Z U X</pair>
    </stimulus-response-pair>
    <stimulus-response-pair>
        <auditory-loop-priority>2</auditory-loop-priority>
        <pair>F E P : Y U F</pair>
    </stimulus-response-pair>
    <stimulus-response-pair>
        <auditory-loop-priority>3</auditory-loop-priority>
        <pair>H A J : P O B</pair>
    </stimulus-response-pair>
	<stimulus-response-pair>
        <auditory-loop-priority>4</auditory-loop-priority>
        <pair>N A F : K E J</pair>
    </stimulus-response-pair><stimulus-response-pair>
        <auditory-loop-priority>6</auditory-loop-priority>
        <pair>M I V : T U J</pair>
    </stimulus-response-pair><stimulus-response-pair>
        <auditory-loop-priority>8</auditory-loop-priority>
        <pair>T E V : V A B</pair>
    </stimulus-response-pair><stimulus-response-pair>
        <auditory-loop-priority>12</auditory-loop-priority>
        <pair>K E F : V U K</pair>
    </stimulus-response-pair><stimulus-response-pair>
        <auditory-loop-priority>11</auditory-loop-priority>
        <pair>P I J : Z I B</pair>
		</stimulus-response-pair><stimulus-response-pair>
        <auditory-loop-priority>10</auditory-loop-priority>
        <pair>M E V : F U P</pair>
		</stimulus-response-pair><stimulus-response-pair>
        <auditory-loop-priority>9</auditory-loop-priority>
        <pair>Z U D : J I D</pair>
		</stimulus-response-pair><stimulus-response-pair>
        <auditory-loop-priority>7</auditory-loop-priority>
        <pair>P E J : V A W</pair>
		</stimulus-response-pair><stimulus-response-pair>
        <auditory-loop-priority>5</auditory-loop-priority>
        <pair>W A F : Y O J</pair>
    </stimulus-response-pair>
    <fast-presentation>
        <percentage-correct>
            <percentage-correct-data>0.5</percentage-correct-data>
            <percentage-correct-data>1.0</percentage-correct-data>
            <percentage-correct-data>1.5</percentage-correct-data>
            <percentage-correct-data>2.8</percentage-correct-data>
            <percentage-correct-data>3.3</percentage-correct-data>
            <percentage-correct-data>3.7</percentage-correct-data>
            <percentage-correct-data>3.75</percentage-correct-data>
            <percentage-correct-data>4.3</percentage-correct-data>
            <percentage-correct-data>5.0</percentage-correct-data>
            <percentage-correct-data>5.5</percentage-correct-data>
        </percentage-correct>
        <cumulative-errors>
            <cumulative-errors-data>
                <pair>B I W : Z U X</pair>
                <cumulative-error>1</cumulative-error>
            </cumulative-errors-data>
            <cumulative-errors-data>
                <pair>F E P : Y U F</pair>
                <cumulative-error>3</cumulative-error>
            </cumulative-errors-data>
            <cumulative-errors-data>
                <pair>H A J : P O B</pair>
                <cumulative-error>7</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>N A F : K E J</pair>
                <cumulative-error>13</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>M I V : T U J</pair>
                <cumulative-error>20</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>T E V : V A B</pair>
                <cumulative-error>28</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>K E F : V U K</pair>
                <cumulative-error>38</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>P I J : Z I B</pair>
                <cumulative-error>48</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>M E V : F U P</pair>
                <cumulative-error>56</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>Z U D : J I D</pair>
                <cumulative-error>62</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>P E J : V A W</pair>
                <cumulative-error>67</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>W A F : Y O J</pair>
                <cumulative-error>71</cumulative-error>
            </cumulative-errors-data>
        </cumulative-errors>
    </fast-presentation>
    <slow-presentation>
        <percentage-correct>
            <percentage-correct-data>0.6</percentage-correct-data>
            <percentage-correct-data>1.4</percentage-correct-data>
            <percentage-correct-data>2.8</percentage-correct-data>
            <percentage-correct-data>3.7</percentage-correct-data>
            <percentage-correct-data>4.5</percentage-correct-data>
            <percentage-correct-data>5.0</percentage-correct-data>
            <percentage-correct-data>5.6</percentage-correct-data>
            <percentage-correct-data>6.6</percentage-correct-data>
            <percentage-correct-data>6.65</percentage-correct-data>
            <percentage-correct-data>7.4</percentage-correct-data>
        </percentage-correct>
        <cumulative-errors>
            <cumulative-errors-data>
                <pair>B I W : Z U X</pair>
                <cumulative-error>1</cumulative-error>
            </cumulative-errors-data>
            <cumulative-errors-data>
                <pair>F E P : Y U F</pair>
                <cumulative-error>2</cumulative-error>
            </cumulative-errors-data>
            <cumulative-errors-data>
                <pair>H A J : P O B</pair>
                <cumulative-error>3</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>N A F : K E J</pair>
                <cumulative-error>5</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>M I V : T U J</pair>
                <cumulative-error>8</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>T E V : V A B</pair>
                <cumulative-error>12</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>K E F : V U K</pair>
                <cumulative-error>16</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>P I J : Z I B</pair>
                <cumulative-error>19</cumulative-error>				
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>M E V : F U P</pair>
                <cumulative-error>22</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>Z U D : J I D</pair>
                <cumulative-error>25</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>P E J : V A W</pair>
                <cumulative-error>28</cumulative-error>
            </cumulative-errors-data>
			<cumulative-errors-data>
                <pair>W A F : Y O J</pair>
                <cumulative-error>30</cumulative-error>
            </cumulative-errors-data>
        </cumulative-errors>
    </slow-presentation>
</experiment>

=== jonsubs/chrest/scripted-experiment-inputs/PairedAssociateFastSlow/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<experiment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="schema.xsd">
    <stimulus-response-pair>
        <auditory-loop-priority>3</auditory-loop-priority>
        <pair>F E P : H A J</pair>
    </stimulus-response-pair>
    <stimulus-response-pair>
        <auditory-loop-priority>2</auditory-loop-priority>
        <pair>Z U X : M A F</pair>
    </stimulus-response-pair>
    <stimulus-response-pair>
        <auditory-loop-priority>1</auditory-loop-priority>
        <pair>P I J : Y U F</pair>
    </stimulus-response-pair>
    <fast-presentation>
        <percentage-correct>
            <percentage-correct-data>0.5</percentage-correct-data>
            <percentage-correct-data>1.0</percentage-correct-data>
            <percentage-correct-data>1.5</percentage-correct-data>
            <percentage-correct-data>2.8</percentage-correct-data>
            <percentage-correct-data>3.3</percentage-correct-data>
            <percentage-correct-data>3.7</percentage-correct-data>
            <percentage-correct-data>3.75</percentage-correct-data>
            <percentage-correct-data>4.3</percentage-correct-data>
            <percentage-correct-data>5.0</percentage-correct-data>
            <percentage-correct-data>5.5</percentage-correct-data>
        </percentage-correct>
        <cumulative-errors>
            <cumulative-errors-data>
                <pair>F E P : H A J</pair>
                <cumulative-error>5</cumulative-error>
            </cumulative-errors-data>
            <cumulative-errors-data>
                <pair>Z U X : M A F</pair>
                <cumulative-error>6</cumulative-error>
            </cumulative-errors-data>
            <cumulative-errors-data>
                <pair>P I J : Y U F</pair>
                <cumulative-error>7</cumulative-error>
            </cumulative-errors-data>
        </cumulative-errors>
    </fast-presentation>
    <slow-presentation>
        <percentage-correct>
            <percentage-correct-data>0.6</percentage-correct-data>
            <percentage-correct-data>1.4</percentage-correct-data>
            <percentage-correct-data>2.8</percentage-correct-data>
            <percentage-correct-data>3.7</percentage-correct-data>
            <percentage-correct-data>4.5</percentage-correct-data>
            <percentage-correct-data>5.0</percentage-correct-data>
            <percentage-correct-data>5.6</percentage-correct-data>
            <percentage-correct-data>6.6</percentage-correct-data>
            <percentage-correct-data>6.65</percentage-correct-data>
            <percentage-correct-data>7.4</percentage-correct-data>
        </percentage-correct>
        <cumulative-errors>
            <cumulative-errors-data>
                <pair>F E P : H A J</pair>
                <cumulative-error>4</cumulative-error>
            </cumulative-errors-data>
            <cumulative-errors-data>
                <pair>Z U X : M A F</pair>
                <cumulative-error>3</cumulative-error>
            </cumulative-errors-data>
            <cumulative-errors-data>
                <pair>P I J : Y U F</pair>
                <cumulative-error>6</cumulative-error>
            </cumulative-errors-data>
        </cumulative-errors>
    </slow-presentation>
</experiment>
